### ISSUE TITLE
Fallo en Travis CI y test

### ISSUE THREAD

**Issue by ricardossmadrid** [MiriamSP/SpaiEcp2MiriamSanz#10]
Buenas tardes @MiriamSP,

Estoy viendo que hay problemas para la conexión con Travis CI.

No estoy muy seguro pero, creo que no está puesto el nombre del archivo correctamente en el proyecto.

Existente: travis.yml
Necesario: .travis.yml

Faltaría el punto(.) en el nombre del archivo del proyecto.

Por otra parte, deberías abrir la posibilidad de realizar todos los test de una sóla vez en el archivo AllIwvgJunittest, puesto que se encuentran comentados.

Muchas gracias y un saludo,

Ricardo Sánchez

**Comment by MiriamSP** [comment]
Gracias Ricardo,
- Cambie el el nombre del fichero (añadiendo el . por delante), desde gitHub.
- Volví a arrancar este repositorio desde Travis 

Pero sigo con el problema, sabes como puedo solucionarlo? 

Gracias otra vez!

Un saludo

Miriam

**Comment by ricardossmadrid** [comment]
Buenas Miriam,

Siendo sincero no lo sé. En estas semanas es la primera vez que utilizo estas herramientas.

Por lo que veo, sigue sin reconocer el archivo .travis.yml desde travis CI:

![image](https://cloud.githubusercontent.com/assets/14840911/10292504/e93dcc78-6baf-11e5-9ea0-7c1e178fb8bb.png)

Menciono a los otros compañeros @chema9355 y @davidereselmejor para ver si nos pueden ayudar.

Espero se solucione pronto.

Un saludo,

Ricardo Sánchez

**Comment by chema9355** [comment]
Si te metes en teavian ci, en el repositorio y le das a last build, que fallo te da?

Enviado desde mi smartphone Sony Xperia™

---- ricardossmadrid escribió ----

**Comment by MiriamSP** [comment]
Me sigue dando el mismo error, que no encuentra el fichero .travis.yml.

![travis](https://cloud.githubusercontent.com/assets/14840898/10293585/9015d7de-6bb5-11e5-8bd8-f64e992b3f34.jpg)

NO se si como subió con el fichero incorrecto se ha quedado algo "pinzado", aunque arranque nuevamente desde Travis.

Gracias

Miriam

**Comment by ricardossmadrid** [comment]
Quizá sobre el comentario puesto que ya estés al tanto pero, comprueba que tienes el fichero .travis.yml en la última versión en la que haces Push.

Es decir, sube la rama develop arriba en la historia de ramas, comprueba que está el fichero de travis en la raíz del proyecto:

![image](https://cloud.githubusercontent.com/assets/14840911/10294161/dd1e7498-6bb8-11e5-831c-7363723f056e.png)

Y, por último, haz el push hacia el repositorio remoto.

Estos fueron los pasos que realicé yo y espero que te ayuden.

Un saludo,

Ricardo Sánchez

**Comment by MiriamSP** [comment]
He comprobado y tengo el fichero .travis.yml.

He subido la rama develop y actualizado el repositorio, pero sigo igual:

![rep_ramas](https://cloud.githubusercontent.com/assets/14840898/10294731/6ada1280-6bbc-11e5-9cb5-51ba759fd62c.jpg)

Muchas gracias por la ayuda, esta mañana escribí a Jesús Bernal, a ver si consigue decirme como solucionarlo.
Si lo consigo, os lo comento por si tenéis curiosidad.

Miriam

**Comment by MiriamSP** [comment]
Release-1.0 Realizada
